/**
 * POST /api/v1/analyze  (redirected to this function — see netlify.toml)
 * Body: { brand: string }
 * Header: Authorization: Bearer bb_live_...
 *
 * The real public API endpoint documented in ApiDocs.tsx and generated by
 * Developers.tsx > API Keys. Authenticated with a Presora API key, not a
 * user session — see _lib/apiKeyAuth.js. Runs the same scan core as the
 * in-app scan (analyze.js) and persists the result the same way, so a key
 * holder's programmatic scans show up in their Reports the same as manual
 * ones.
 */
import { createClient } from '@supabase/supabase-js';
import ws from 'ws';
import { OPENROUTER_MODELS, runBrandScan } from './_lib/runScan.js';
import { verifyApiKey } from './_lib/apiKeyAuth.js';
import { fireWebhooksForEvent } from './_lib/webhookDelivery.js';

if (!globalThis.WebSocket) globalThis.WebSocket = ws;

const SUPABASE_URL = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_KEY;

const PLAN_TIER = { free: 0, starter: 1, solo: 1, growth: 2, enterprise: 2, agency: 2 };

const RATE_LIMIT_WINDOW_MS = 60_000;
const MAX_REQUESTS_PER_WINDOW = 10;
const requestStore = new Map();
const shouldRateLimit = (key) => {
  const current = Date.now();
  const entry = requestStore.get(key) || { count: 0, windowStart: current };
  if (current - entry.windowStart > RATE_LIMIT_WINDOW_MS) {
    entry.windowStart = current;
    entry.count = 0;
  }
  entry.count += 1;
  requestStore.set(key, entry);
  return entry.count > MAX_REQUESTS_PER_WINDOW;
};

export const handler = async (event) => {
  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ error: 'Method not allowed' }) };
  }
  if (event.body && event.body.length > 4 * 1024) {
    return { statusCode: 413, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ error: 'Payload too large' }) };
  }

  let supabaseAdmin;
  try {
    supabaseAdmin = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY, {
      auth: { autoRefreshToken: false, persistSession: false },
    });
  } catch (err) {
    console.error('api-analyze: Supabase client init failed:', err.message);
    return { statusCode: 500, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ error: 'Server misconfiguration' }) };
  }

  const auth = await verifyApiKey(supabaseAdmin, event.headers.authorization || event.headers.Authorization);
  if (!auth) {
    return { statusCode: 401, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ error: 'Invalid or revoked API key' }) };
  }

  if (shouldRateLimit(auth.userId)) {
    return { statusCode: 429, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ error: 'Rate limit exceeded' }) };
  }

  let brandName;
  try {
    const body = JSON.parse(event.body || '{}');
    brandName = String(body.brand || '').trim().slice(0, 500);
  } catch {
    return { statusCode: 400, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ error: 'Invalid JSON' }) };
  }
  if (!brandName) {
    return { statusCode: 400, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ error: '"brand" is required' }) };
  }

  try {
    const { data: profile } = await supabaseAdmin.from('profiles').select('plan').eq('id', auth.userId).single();
    const planTier = PLAN_TIER[String(profile?.plan || 'free').toLowerCase()] ?? 0;
    const models = OPENROUTER_MODELS.filter((m) => m.tier <= planTier);

    const result = await runBrandScan({ supabaseAdmin, target: brandName, models, userId: auth.userId });

    const { data: saved, error: insertError } = await supabaseAdmin
      .from('analyses')
      .insert({
        user_id: auth.userId,
        brand_name: brandName,
        trust_score: result.trustScore,
        authority: result.authority,
        sentiment: result.sentiment,
        recency: result.recency,
        mentions: result.mentions,
        accuracy: result.accuracy,
        sources: result.sources,
      })
      .select('id, created_at')
      .single();
    if (insertError) console.error('api-analyze: failed to save analysis:', insertError.message);

    const responseBody = { id: saved?.id ?? null, brandName, createdAt: saved?.created_at ?? new Date().toISOString(), ...result };

    fireWebhooksForEvent(supabaseAdmin, { userId: auth.userId, event: 'analysis.completed', payload: responseBody })
      .catch((err) => console.error('api-analyze: webhook firing failed:', err.message));

    return { statusCode: 200, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(responseBody) };
  } catch (err) {
    console.error('api-analyze handler error:', err.message);
    fireWebhooksForEvent(supabaseAdmin, { userId: auth.userId, event: 'analysis.failed', payload: { brandName, error: err.message } })
      .catch(() => {});
    return { statusCode: 500, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ error: 'Analysis failed. Please try again.' }) };
  }
};
